# governance/reason_codes.py

class ReasonCodes:

    # =========================
    # GENERAL
    # =========================

    ACTION_ALLOWED_BY_POLICY = "ACTION_ALLOWED_BY_POLICY"

    NOT_ENOUGH_GOVERNANCE_DATA = "NOT_ENOUGH_GOVERNANCE_DATA"

    GOVERNANCE_SCOPE_CONFLICT_DETECTED = "GOVERNANCE_SCOPE_CONFLICT_DETECTED"

    HUMAN_CONFIRMATION_REQUIRED = "HUMAN_CONFIRMATION_REQUIRED"

    # =========================
    # HUMAN / TRUST
    # =========================

    HUMAN_PROHIBITION_ACTIVE = "HUMAN_PROHIBITION_ACTIVE"

    BASIC_TRUST_REQUIRES_CONFIRMATION = "BASIC_TRUST_REQUIRES_CONFIRMATION"

    DELEGATED_AUTONOMY_NOT_ALLOWED = "DELEGATED_AUTONOMY_NOT_ALLOWED"

    AUTONOMY_SCOPE_EXPIRED = "AUTONOMY_SCOPE_EXPIRED"

    AUTONOMY_SCOPE_NOT_REVALIDATED = "AUTONOMY_SCOPE_NOT_REVALIDATED"

    # =========================
    # SENSITIVE DOMAINS
    # =========================

    SENSITIVE_DOMAIN_UNKNOWN = "SENSITIVE_DOMAIN_UNKNOWN"

    SENSITIVE_DOMAIN_PROTECTED = "SENSITIVE_DOMAIN_PROTECTED"

    SENSITIVE_DOMAIN_REQUIRES_CONFIRMATION = (
        "SENSITIVE_DOMAIN_REQUIRES_CONFIRMATION"
    )

    SENSITIVE_DOMAIN_EXTERNAL_RESTRICTED = (
        "SENSITIVE_DOMAIN_EXTERNAL_RESTRICTED"
    )

    SENSITIVE_DOMAIN_MEMORY_RESTRICTED = (
        "SENSITIVE_DOMAIN_MEMORY_RESTRICTED"
    )

    # =========================
    # REVERSIBILITY
    # =========================

    LOW_REVERSIBILITY_ACTION = "LOW_REVERSIBILITY_ACTION"

    IRREVERSIBLE_ACTION_REQUIRES_CONFIRMATION = (
        "IRREVERSIBLE_ACTION_REQUIRES_CONFIRMATION"
    )

    # =========================
    # MEMORY
    # =========================

    MEMORY_WRITE_NOT_ALLOWED = "MEMORY_WRITE_NOT_ALLOWED"

    INNER_CORE_WRITE_FORBIDDEN = "INNER_CORE_WRITE_FORBIDDEN"

    MEMORY_SCOPE_RESTRICTED = "MEMORY_SCOPE_RESTRICTED"

    MEMORY_TARGET_UNKNOWN = "MEMORY_TARGET_UNKNOWN"

    # =========================
    # EXTERNAL COMMUNICATION
    # =========================

    EXTERNAL_COMMUNICATION_RESTRICTED = (
        "EXTERNAL_COMMUNICATION_RESTRICTED"
    )

    EXTERNAL_TARGET_NOT_ALLOWED = "EXTERNAL_TARGET_NOT_ALLOWED"

    PUBLIC_ONLY_ALLOWED = "PUBLIC_ONLY_ALLOWED"

    PUBLIC_FILTER_REQUIRED = "PUBLIC_FILTER_REQUIRED"

    EXTERNAL_AI_RESTRICTED = "EXTERNAL_AI_RESTRICTED"

    INTERNET_ACCESS_RESTRICTED = "INTERNET_ACCESS_RESTRICTED"

    TRUSTED_PERSON_ONLY = "TRUSTED_PERSON_ONLY"

    # =========================
    # VISIBILITY / FILTERING
    # =========================

    VISIBILITY_SCOPE_RESTRICTED = "VISIBILITY_SCOPE_RESTRICTED"

    INTERNAL_DATA_BLOCKED = "INTERNAL_DATA_BLOCKED"

    RAW_INTERNAL_REASONING_BLOCKED = (
        "RAW_INTERNAL_REASONING_BLOCKED"
    )

    INNER_CORE_DATA_BLOCKED = "INNER_CORE_DATA_BLOCKED"

    SANITIZER_REQUIRED = "SANITIZER_REQUIRED"

    SANITIZER_NOT_IMPLEMENTED = "SANITIZER_NOT_IMPLEMENTED"

    # =========================
    # EMERGENCY
    # =========================

    PROJECTED_EMERGENCY_NOT_AUTHORIZATION = (
        "PROJECTED_EMERGENCY_NOT_AUTHORIZATION"
    )

    FACTUAL_EMERGENCY_POLICY_ALLOWED = (
        "FACTUAL_EMERGENCY_POLICY_ALLOWED"
    )

    FACTUAL_EMERGENCY_POLICY_NOT_ALLOWED = (
        "FACTUAL_EMERGENCY_POLICY_NOT_ALLOWED"
    )

    EMERGENCY_SCOPE_RESTRICTED = "EMERGENCY_SCOPE_RESTRICTED"

    # =========================
    # TEMPORAL / POLICY
    # =========================

    POLICY_EXPIRED = "POLICY_EXPIRED"

    POLICY_NOT_REVALIDATED = "POLICY_NOT_REVALIDATED"

    POLICY_SOURCE_UNKNOWN = "POLICY_SOURCE_UNKNOWN"

    POLICY_VERSION_MISSING = "POLICY_VERSION_MISSING"

    # =========================
    # AUDIT / TRACE
    # =========================

    GOVERNANCE_TRACE_REQUIRED = "GOVERNANCE_TRACE_REQUIRED"

    GOVERNANCE_AUDIT_REQUIRED = "GOVERNANCE_AUDIT_REQUIRED"

    RULE_HIT_RECORDED = "RULE_HIT_RECORDED"
