STUDY_CODE = "decision_under_uncertainty"

NEXT_BLOCK_RESERVED = "NEXT_BLOCK_RESERVED"

WORK_BRANCH_RESERVED = "WORK_BRANCH_RESERVED"
MIXED_BRANCH_RESERVED = "MIXED_BRANCH_RESERVED"
LIFE_BRANCH_RESERVED = "LIFE_BRANCH_RESERVED"