QUESTION_BANK_ES = {
    "DU1": {
        "question_id": "22222222-0000-4000-8000-000000000001",
        "code": "DU1",
        "version": 1,
        "block": "DU",
        "family": "decision_under_uncertainty",
        "domain": "context",
        "type": "single_select",
        "prompt": "¿Cuál de las siguientes opciones describe mejor su estilo de vida?",
        "options": [
            {"value": 0, "text": "Tranquilo, predecible y rutinario"},
            {"value": 1, "text": "Ocasionalmente surgen situaciones nuevas en mi vida o trabajo"},
            {"value": 2, "text": "Periódicamente tengo que adaptarme a situaciones nuevas"},
            {"value": 3, "text": "Con frecuencia tengo que adaptarme a nuevas situaciones en mi vida o trabajo"},
            {"value": 4, "text": "Casi constantemente tengo que responder rápidamente a nuevas situaciones en mi vida o trabajo"},
            {"value": 5, "text": "Mi vida o trabajo se caracterizan por una incertidumbre constante y condiciones que cambian rápidamente"},
        ],
        "score_direction": "higher_is_more_risk",
        "status": "active",
    },

    "DU2": {
        "question_id": "22222222-0000-4000-8000-000000000002",
        "code": "DU2",
        "version": 1,
        "block": "DU",
        "family": "observed_experience",
        "domain": "context",
        "type": "single_select",
        "prompt": "¿Con qué frecuencia otras personas le piden ayuda en situaciones difíciles o inesperadas?",
        "options": [
            {"value": 0, "text": "Casi nunca"},
            {"value": 1, "text": "Rara vez"},
            {"value": 2, "text": "A veces"},
            {"value": 3, "text": "Con bastante frecuencia"},
            {"value": 4, "text": "Con frecuencia"},
            {"value": 5, "text": "Muy frecuentemente"},
        ],
        "score_direction": "higher_is_more_observed_experience",
        "status": "active",
    },

    "DU3": {
        "question_id": "22222222-0000-4000-8000-000000000003",
        "code": "DU3",
        "version": 1,
        "block": "DU",
        "family": "external_confirmation",
        "domain": "context",
        "type": "single_select",
        "prompt": "¿Con qué frecuencia otras personas comentan que sus acciones ayudaron a resolver una situación difícil o inesperada?",
        "options": [
            {"value": 0, "text": "Generalmente pasa desapercibido"},
            {"value": 1, "text": "Muy rara vez lo mencionan"},
            {"value": 2, "text": "A veces lo mencionan"},
            {"value": 3, "text": "Con bastante frecuencia lo mencionan"},
            {"value": 4, "text": "Con frecuencia lo mencionan"},
            {"value": 5, "text": "Casi siempre lo mencionan"},
        ],
        "score_direction": "higher_is_more_external_confirmation",
        "status": "active",
    },

    "DU4": {
        "question_id": "22222222-0000-4000-8000-000000000004",
        "code": "DU4",
        "version": 1,
        "block": "DU",
        "family": "experience_context_router",
        "domain": "routing",
        "type": "single_select",
        "prompt": "¿Dónde ocurre esto con mayor frecuencia?",
        "options": [
            {"value": 0, "text": "Principalmente en el trabajo"},
            {"value": 1, "text": "Tanto en el trabajo como en mi vida personal"},
            {"value": 2, "text": "Principalmente en mi vida personal"},
        ],
        "score_direction": "routing_only",
        "status": "active",
    },
}