QUESTION_BANK_RU = {'DU1': {'question_id': '22222222-0000-4000-8000-000000000001',
         'code': 'DU1',
         'version': 1,
         'block': 'DU',
         'family': 'decision_under_uncertainty',
         'domain': 'context',
         'type': 'single_select',
         'prompt': 'Что характерно для вашего образа жизни?',
         'options': [{'value': 0, 'text': 'Спокойный и размеренный, однотипный'},
                     {'value': 1, 'text': 'Иногда в жизни или работе появляются новые условия'},
                     {'value': 2, 'text': 'Периодически приходится подстраиваться под новые условия'},
                     {'value': 3, 'text': 'Часто приходится подстраиваться под новые условия жизни или работы'},
                     {'value': 4,
                      'text': 'Почти постоянно приходится быстро реагировать на новые условия жизни или работы'},
                     {'value': 5, 'text': 'Вся жизнь или работа: постоянная неизвестность, быстро меняющиеся условия'}],
         'score_direction': 'higher_is_more_risk',
         'status': 'active',
         'scale_type': 'ordinal'},
 'DU2': {'question_id': '22222222-0000-4000-8000-000000000002',
         'code': 'DU2',
         'version': 1,
         'block': 'DU',
         'family': 'observed_experience',
         'domain': 'context',
         'type': 'single_select',
         'prompt': 'Как часто окружающие обращаются к вам за помощью в сложной или неожиданной ситуации?',
         'options': [{'value': 0, 'text': 'Практически никогда'},
                     {'value': 1, 'text': 'Редко'},
                     {'value': 2, 'text': 'Иногда'},
                     {'value': 3, 'text': 'Довольно часто'},
                     {'value': 4, 'text': 'Часто'},
                     {'value': 5, 'text': 'Очень часто'}],
         'score_direction': 'higher_is_more_observed_experience',
         'status': 'active',
         'scale_type': 'ordinal'},
 'DU3': {'question_id': '22222222-0000-4000-8000-000000000003',
         'code': 'DU3',
         'version': 1,
         'block': 'DU',
         'family': 'external_confirmation',
         'domain': 'context',
         'type': 'single_select',
         'prompt': 'Как часто окружающие отмечают, что именно ваши действия помогли справиться со сложной или '
                   'неожиданной ситуацией?',
         'options': [{'value': 0, 'text': 'Обычно это остаётся незамеченным'},
                     {'value': 1, 'text': 'Замечают очень редко'},
                     {'value': 2, 'text': 'Иногда отмечают'},
                     {'value': 3, 'text': 'Довольно часто отмечают'},
                     {'value': 4, 'text': 'Часто отмечают'},
                     {'value': 5, 'text': 'Практически всегда отмечают'}],
         'score_direction': 'higher_is_more_external_confirmation',
         'status': 'active',
         'scale_type': 'ordinal'},
 'DU4': {'question_id': '22222222-0000-4000-8000-000000000004',
         'code': 'DU4',
         'version': 1,
         'block': 'DU',
         'family': 'experience_context_router',
         'domain': 'routing',
         'type': 'single_select',
         'prompt': 'Где это чаще происходит?',
         'options': [{'value': 0, 'text': 'В основном на работе'},
                     {'value': 1, 'text': 'И на работе, и в личной жизни'},
                     {'value': 2, 'text': 'В основном в личной жизни'}],
         'score_direction': 'routing_only',
         'status': 'active',
         'scale_type': 'ordinal'}}
