QUESTION_BANK_EN = {
    "DU1": {
        "question_id": "22222222-0000-4000-8000-000000000001",
        "code": "DU1",
        "version": 1,
        "block": "DU",
        "family": "decision_under_uncertainty",
        "domain": "context",
        "type": "single_select",
        "prompt": "Which best describes your lifestyle?",
        "options": [
            {"value": 0, "text": "Calm, predictable, and routine"},
            {"value": 1, "text": "New situations occasionally arise in my life or work"},
            {"value": 2, "text": "I periodically have to adapt to new situations"},
            {"value": 3, "text": "I often have to adapt to new situations in life or work"},
            {"value": 4, "text": "I almost constantly have to respond quickly to new situations in life or work"},
            {"value": 5, "text": "My life or work is characterized by constant uncertainty and rapidly changing conditions"},
        ],
        "score_direction": "higher_is_more_risk",
        "status": "active",
    },

    "DU2": {
        "question_id": "22222222-0000-4000-8000-000000000002",
        "code": "DU2",
        "version": 1,
        "block": "DU",
        "family": "observed_experience",
        "domain": "context",
        "type": "single_select",
        "prompt": "How often do other people ask you for help in difficult or unexpected situations?",
        "options": [
            {"value": 0, "text": "Almost never"},
            {"value": 1, "text": "Rarely"},
            {"value": 2, "text": "Sometimes"},
            {"value": 3, "text": "Fairly often"},
            {"value": 4, "text": "Often"},
            {"value": 5, "text": "Very often"},
        ],
        "score_direction": "higher_is_more_observed_experience",
        "status": "active",
    },

    "DU3": {
        "question_id": "22222222-0000-4000-8000-000000000003",
        "code": "DU3",
        "version": 1,
        "block": "DU",
        "family": "external_confirmation",
        "domain": "context",
        "type": "single_select",
        "prompt": "How often do other people say that your actions helped resolve a difficult or unexpected situation?",
        "options": [
            {"value": 0, "text": "It usually goes unnoticed"},
            {"value": 1, "text": "Very rarely"},
            {"value": 2, "text": "Sometimes"},
            {"value": 3, "text": "Fairly often"},
            {"value": 4, "text": "Often"},
            {"value": 5, "text": "Almost always"},
        ],
        "score_direction": "higher_is_more_external_confirmation",
        "status": "active",
    },

    "DU4": {
        "question_id": "22222222-0000-4000-8000-000000000004",
        "code": "DU4",
        "version": 1,
        "block": "DU",
        "family": "experience_context_router",
        "domain": "routing",
        "type": "single_select",
        "prompt": "Where does this happen most often?",
        "options": [
            {"value": 0, "text": "Mostly at work"},
            {"value": 1, "text": "Both at work and in my personal life"},
            {"value": 2, "text": "Mostly in my personal life"},
        ],
        "score_direction": "routing_only",
        "status": "active",
    },
}