QUESTION_BANK_RU = {'pp1': {'scale_type': 'interval',
         'value_type': 'float',
         'allowed_values': [0],
         'value_constraint_type': 'range',
         'allowed_range': {'min': None, 'max': None, 'step': 1},
         'question_id': '9c82a506-b85a-47f6-9eba-9a205d57a1f4',
         'code': 'pp1',
         'version': 1,
         'block': 'DU',
         'family': 'decision_under_uncertainty',
         'domain': 'context',
         'type': 'single_select',
         'prompt': 'hhhhhooo',
         'options': [{'value': 0, 'text': '', 'next_code': ''}],
         'score_direction': 'not_scored',
         'status': 'draft',
         'question_block': 'DU',
         'question_number_in_block': 1,
         'question_version': 1,
         'question_type': 'single_select',
         'scale': {'scale_type': 'interval',
                   'min': None,
                   'max': None,
                   'step': None,
                   'labels': {'left': None, 'right': None},
                   'direction': 'not_scored',
                   'unit': None},
         'answer_options': [{'value': 0, 'text': '', 'next_code': ''}],
         'routing': {'default_next': None, 'option_next_codes': [{'value': 0, 'next_code': None}]}}}
