CHECK_REGISTRY = {
    "data_available": "check_variable_has_data",
    "scale_defined": "check_scale_defined",
    "scale_pattern_supported": "check_scale_pattern_supported",
    "paired_observations": "check_paired_observations",
    "minimum_complete_pairs": "check_minimum_complete_pairs",
    "not_constant_variable": "check_not_constant_variable",
    "monotonic_relationship_plausible": "check_monotonic_relationship_plausible",
    "numeric_data": "check_numeric_data",
    "linear_relationship_plausible": "check_linear_relationship_plausible",
    "no_extreme_outliers": "check_extreme_outliers_iqr",
    "approximately_normal_outcome_within_groups_or_sufficient_sample_size": "check_approximately_normal_or_sufficient_sample",
    "independent_observations": "check_independent_observations",
    "two_groups": "check_two_groups",
    "three_or_more_groups": "check_three_or_more_groups",
    "minimum_group_size": "check_minimum_group_size",
    "group_balance": "check_group_balance",
    "variance_assumption_checked": "check_variance_assumption",
    "contingency_table": "check_contingency_table",
    "expected_cell_counts": "check_expected_cell_counts",
    "two_by_two_table": "check_two_by_two_table",
}